server:
  port: ${PORT:8011}
spring:
  application:
    name: game-service
  cloud:
    consul:
      enabled: false
app:
  achievement:
    ids:
      a-new-cruncher-is-born: "f16f702d-b013-4d5c-89cc-5a971f638e52"
      connect-discord: "2856aa81-75e4-438b-8942-215006d17a9b"
      connect-twitter: "d33ff7b8-232a-462f-a4fd-a2f889783247"
      connect-github: "3ba63d0d-0b5d-48db-9d04-bc60979d7dc9"
  messaging:
    exchange:
      user: "user"
      connection: "connection"
      achievement: "achievement"
    queue:
      user:
        event:
          created: "user.event.created.${spring.application.name}"
      connection:
        event:
          created: "connection.event.created.${spring.application.name}"
    routing-key:
      user:
        event:
          created: "user.event.created"
      connection:
        event:
          created: "connection.event.created"
      achievement:
        command:
          increment: "achievement.command.increment"
          set: "achievement.command.set"
          unlock: "achievement.command.unlock"
